permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
baseurl: ""
url: "http://blog.bioguid.org"
highlighter: pygments

collections:
  docs:
    output: true

markdown: kramdown

repository: https://github.com/GlobalNamesArchitecture/bioguid

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
